server:
  port: 8080
spring:
  application:
    name: bm-shop-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/bm-shop
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangpham1618@gmail.com
    password: prkz ifiz ukyi plai
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000